version: '3'

services: 
# 后端
    java:
        image: ascdc/jdk8
        restart: always
        container_name: TeChat_backEnd
        environment:
            MYSQL_ADDRESS: "TeChat_MySQL:3306"
            MYSQL_USERNAME: "root"
            MYSQL_PASSWORD: "ui234aerasdf35fhhjdf56yk7ne"
            REDIS_HOST: "TeChat_redis"
            REDIS_PORT: "6379"
            # WECHAT_APP_ID: "test"
            # WECHAT_APP_SECRET: "test"
        ports:
        # 外部端口:内部端口
          - "8080:8080"
          - "465:465"
        volumes:
            - ./data/backEnd/index.jar:/data/index.jar
        # 这是java项目的环境变量，yml文件配置
        entrypoint: java -jar /data/index.jar 
        depends_on:
            - redis
            - mysql
        links:
            - redis
            - mysql
        networks:
            - Server
# 前端
    frontEnd:
        image: nginx
        container_name: TeChat_nginx
        restart: always
        volumes:
            - ./data/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./data/frontEnd/dist:/usr/share/nginx/html
        ports:
            - "81:8000"
# 数据库
    mysql:
        image: mysql:5.7.16
        restart: always
        container_name: TeChat_MySQL
        environment:
            # 时区上海
            TZ: Asia/Shanghai
            # root 密码
            MYSQL_ROOT_PASSWORD: "ui234aerasdf35fhhjdf56yk7ne"
            # 初始化数据库(后续的初始化sql会在这个库执行)
            MYSQL_DATABASE: techat
            # 初始化用户(不能是 root 会报错, 后续需要给新用户赋予权限)
            MYSQL_USER: chat
            # 用户密码
            MYSQL_PASSWORD: 12345
            # MYSQL_DATABASE: "seckill"
        command:
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
        # ports:
        #     - "3306:3306"
        volumes:
            - ./data/MySQLData/database/:/var/lib/mysql/
            - ./data/MySQLData/cnf/:/etc/mysql/conf.d/
            - ./data/MySQLData/sql/:/docker-entrypoint-initdb.d/
        networks:
            - Server
# 缓存数据库
    redis: 
        image: redis
        restart: always
        container_name: TeChat_redis
        command: redis-server --appendonly yes
        volumes:
        # 数据目录，要确保先创建好
            - ./data/redisData:/data
        networks:
            - Server
# 内网支持
networks: 
    Server: 
        driver: bridge