version: '3'


services: 
    java:
        image: ascdc/jdk8
        restart: always
        container_name: backEnd
        ports:
        # 外部端口:内部端口
          - "8080:8080"
        volumes:
            - ./data/backEnd/index.jar:/data/index.jar
        # 这是java项目的环境变量，yml文件配置
        entrypoint: java -jar /data/index.jar 
        depends_on:
            - redis
        links:
            - redis
        networks:
            - Todo

    redis: 
        image: redis
        restart: always
        container_name: Todo_redis_1001
        command: redis-server --appendonly yes
        volumes:
        # 数据目录，要确保先创建好
            - ./data/database:/data
        networks:
            - Todo
    frontEnd:
        image: nginx
        restart: always
        volumes:
            - ./data/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./data/frontEnd/dist:/usr/share/nginx/html
        ports:
                - "80:8000"

networks: 
    Todo: 
        driver: bridge
