version: '3'

services: 
# 数据库
    mysql:
        image: mysql:5.7.16
        restart: always
        container_name: recruitSystem_MySQL
        environment:
            # 时区上海
            TZ: Asia/Shanghai
            # root 密码
            MYSQL_ROOT_PASSWORD: "12345"
            # 初始化数据库(后续的初始化sql会在这个库执行)
            MYSQL_DATABASE: PETHOSPITALINFMATION
            # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
            MYSQL_USER: pet
            # 用户密码
            MYSQL_PASSWORD: 12345
            # MYSQL_DATABASE: "seckill"
        command:
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
            --lower_case_table_names=1
        ports:
            - "3307:3306"
        volumes:
            - ./data/MySQLData/database/:/var/lib/mysql/
            - ./data/MySQLData/cnf/:/etc/mysql/conf.d/
            - ./data/MySQLData/sql/:/docker-entrypoint-initdb.d/
# 缓存数据库
    redis: 
        image: redis
        restart: always
        container_name: recruitSystem_redis
        command: redis-server --appendonly yes
        volumes:
        # 数据目录，要确保先创建好
            - ./data/redisData:/data
        ports:
            - "6379:6379"